project_id = "zefmtbhmhgusxhqqddbr"

[functions.scenario-chat]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-stt]
verify_jwt = false

[functions.immergo-chat]
verify_jwt = false

[functions.lesson-chat]
verify_jwt = false

[functions.kokoro-tts]
verify_jwt = false
